pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
                sh 'cd mi-proyecto && mvn clean install'
            }
        }

        stage('Test'){
            steps{
                sh 'mvn test'
            }
        }

        stage('Deploy'){
            steps{
                echo "Simulando un despliegue a un servidor de aplicaciones..."
            }
        }
    }

    post{
        always{
            echo 'El pipeline ha finalizado.'
        }
        success{
            echo 'El pipeline se ha ejecutado con éxito.'
        }
        failure{
            echo 'El pipeline ha fallado.'
        }
    }
}